const movieData = [
  {
    id: 60784,
    url: "https://yts.mx/movies/heart-of-the-hunter-2024",
    imdb_code: "tt28943278",
    title: "Heart of the Hunter",
    title_english: "Heart of the Hunter",
    title_long: "Heart of the Hunter (2024)",
    slug: "heart-of-the-hunter-2024",
    year: 2024,
    rating: 4.7,
    runtime: 105,
    genres: ["Action", "Thriller"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "KSCFWJvcYXE",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/EFACFB49734F907BC46EB67C31E2E135EB9095E4",
        hash: "EFACFB49734F907BC46EB67C31E2E135EB9095E4",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "985.14 MB",
        size_bytes: 1032994161,
        date_uploaded: "2024-03-30 03:21:54",
        date_uploaded_unix: 1711765314,
      },
      {
        url: "https://yts.mx/torrent/download/7A7DA9A9D6484E077585AC168D8D55FB1E8DE3CE",
        hash: "7A7DA9A9D6484E077585AC168D8D55FB1E8DE3CE",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.98 GB",
        size_bytes: 2126008812,
        date_uploaded: "2024-03-30 04:24:10",
        date_uploaded_unix: 1711769050,
      },
    ],
    date_uploaded: "2024-03-30 03:21:54",
    date_uploaded_unix: 1711765314,
  },
  {
    id: 60783,
    url: "https://yts.mx/movies/madu-2024",
    imdb_code: "tt14152882",
    title: "Madu",
    title_english: "Madu",
    title_long: "Madu (2024)",
    slug: "madu-2024",
    year: 2024,
    rating: 6.8,
    runtime: 100,
    genres: ["Biography", "Documentary"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "tPQAlsnhQ34",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/madu_2024/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/madu_2024/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/madu_2024/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/madu_2024/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/madu_2024/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/C7E32346385F7D7C82ED91B24A5EC11CB62F1C93",
        hash: "C7E32346385F7D7C82ED91B24A5EC11CB62F1C93",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "925.73 MB",
        size_bytes: 970698260,
        date_uploaded: "2024-03-29 15:33:21",
        date_uploaded_unix: 1711722801,
      },
      {
        url: "https://yts.mx/torrent/download/B449961BD7CB549A5A1082E62C951D0899FD8B4B",
        hash: "B449961BD7CB549A5A1082E62C951D0899FD8B4B",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.86 GB",
        size_bytes: 1997159793,
        date_uploaded: "2024-03-29 16:38:46",
        date_uploaded_unix: 1711726726,
      },
    ],
    date_uploaded: "2024-03-29 15:33:21",
    date_uploaded_unix: 1711722801,
  },
  {
    id: 60782,
    url: "https://yts.mx/movies/the-beautiful-summer-2023",
    imdb_code: "tt9320170",
    title: "The Beautiful Summer",
    title_english: "The Beautiful Summer",
    title_long: "The Beautiful Summer (2023)",
    slug: "the-beautiful-summer-2023",
    year: 2023,
    rating: 5.5,
    runtime: 111,
    genres: ["Drama"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "xynihKo_UPk",
    language: "it",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/2CB98B00129F05F9821E0E33F711351EDF9B3FEA",
        hash: "2CB98B00129F05F9821E0E33F711351EDF9B3FEA",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 71,
        peers: 36,
        size: "987.49 MB",
        size_bytes: 1035458314,
        date_uploaded: "2024-03-29 15:23:47",
        date_uploaded_unix: 1711722227,
      },
      {
        url: "https://yts.mx/torrent/download/C53574FAF9AA043DA10876C34158A4B928A06058",
        hash: "C53574FAF9AA043DA10876C34158A4B928A06058",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.98 GB",
        size_bytes: 2126008812,
        date_uploaded: "2024-03-29 16:31:55",
        date_uploaded_unix: 1711726315,
      },
    ],
    date_uploaded: "2024-03-29 15:23:47",
    date_uploaded_unix: 1711722227,
  },
  {
    id: 60781,
    url: "https://yts.mx/movies/marinette-2023",
    imdb_code: "tt20251542",
    title: "Marinette",
    title_english: "Marinette",
    title_long: "Marinette (2023)",
    slug: "marinette-2023",
    year: 2023,
    rating: 6.4,
    runtime: 95,
    genres: ["Biography", "Drama", "Sport"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "PCffF20fGHc",
    language: "fr",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/marinette_2023/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/marinette_2023/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/marinette_2023/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/marinette_2023/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/marinette_2023/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/471E02AAFE3BAB254268697050CD0C80B1FDC823",
        hash: "471E02AAFE3BAB254268697050CD0C80B1FDC823",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 57,
        peers: 20,
        size: "847.11 MB",
        size_bytes: 888259215,
        date_uploaded: "2024-03-29 14:47:02",
        date_uploaded_unix: 1711720022,
      },
      {
        url: "https://yts.mx/torrent/download/EA20619F68FC638960D1DD6C3106F6CB136C4CAB",
        hash: "EA20619F68FC638960D1DD6C3106F6CB136C4CAB",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.7 GB",
        size_bytes: 1825361101,
        date_uploaded: "2024-03-29 15:59:17",
        date_uploaded_unix: 1711724357,
      },
    ],
    date_uploaded: "2024-03-29 14:47:02",
    date_uploaded_unix: 1711720022,
  },
  {
    id: 60780,
    url: "https://yts.mx/movies/lousy-carter-2023",
    imdb_code: "tt27774989",
    title: "Lousy Carter",
    title_english: "Lousy Carter",
    title_long: "Lousy Carter (2023)",
    slug: "lousy-carter-2023",
    year: 2023,
    rating: 6.4,
    runtime: 80,
    genres: ["Comedy"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "1Yz7chWMlKI",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/lousy_carter_2023/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/lousy_carter_2023/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/lousy_carter_2023/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/lousy_carter_2023/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/lousy_carter_2023/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/0F63BF90BDB9A9190F66F6238D397BAD188592FF",
        hash: "0F63BF90BDB9A9190F66F6238D397BAD188592FF",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 100,
        peers: 14,
        size: "700.64 MB",
        size_bytes: 734674289,
        date_uploaded: "2024-03-29 11:35:43",
        date_uploaded_unix: 1711708543,
      },
      {
        url: "https://yts.mx/torrent/download/70D0B353C085A6501044B6AF55738A6233F3C3A8",
        hash: "70D0B353C085A6501044B6AF55738A6233F3C3A8",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.41 GB",
        size_bytes: 1513975972,
        date_uploaded: "2024-03-29 12:30:34",
        date_uploaded_unix: 1711711834,
      },
    ],
    date_uploaded: "2024-03-29 11:35:43",
    date_uploaded_unix: 1711708543,
  },
  {
    id: 60779,
    url: "https://yts.mx/movies/the-wages-of-fear-2024",
    imdb_code: "tt27487473",
    title: "The Wages of Fear",
    title_english: "The Wages of Fear",
    title_long: "The Wages of Fear (2024)",
    slug: "the-wages-of-fear-2024",
    year: 2024,
    rating: 5.3,
    runtime: 104,
    genres: ["Action", "Adventure", "Drama", "Thriller"],
    summary:
      "In the middle of the desert, near a refugee camp, an oil well catches fire, directly threatening the lives of the population. Dispatching experts to the site, the company operating the well realizes that it has only one solution to avert the catastrophe: detonate the oil well with nitroglycerin within 24 hours. Against a large sum of money, a powerhouse team is then sent 800 km away to transport 200 kg of explosives in two trucks. The team now has less than 20 hours to reach the oil well. 20 hours to traverse hostile zones controlled by armed rebels, cross minefields, and drive two trucks loaded with nitroglycerin over rough terrain!. The race against the clock has begun.",
    description_full:
      "In the middle of the desert, near a refugee camp, an oil well catches fire, directly threatening the lives of the population. Dispatching experts to the site, the company operating the well realizes that it has only one solution to avert the catastrophe: detonate the oil well with nitroglycerin within 24 hours. Against a large sum of money, a powerhouse team is then sent 800 km away to transport 200 kg of explosives in two trucks. The team now has less than 20 hours to reach the oil well. 20 hours to traverse hostile zones controlled by armed rebels, cross minefields, and drive two trucks loaded with nitroglycerin over rough terrain!. The race against the clock has begun.",
    synopsis:
      "In the middle of the desert, near a refugee camp, an oil well catches fire, directly threatening the lives of the population. Dispatching experts to the site, the company operating the well realizes that it has only one solution to avert the catastrophe: detonate the oil well with nitroglycerin within 24 hours. Against a large sum of money, a powerhouse team is then sent 800 km away to transport 200 kg of explosives in two trucks. The team now has less than 20 hours to reach the oil well. 20 hours to traverse hostile zones controlled by armed rebels, cross minefields, and drive two trucks loaded with nitroglycerin over rough terrain!. The race against the clock has begun.",
    yt_trailer_code: "",
    language: "fr",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/the_wages_of_fear_2024/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/the_wages_of_fear_2024/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/the_wages_of_fear_2024/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/the_wages_of_fear_2024/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/the_wages_of_fear_2024/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/9C1F6141FBEBD2A614D3A72EE7DB1E096A0BC261",
        hash: "9C1F6141FBEBD2A614D3A72EE7DB1E096A0BC261",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 100,
        peers: 90,
        size: "975.73 MB",
        size_bytes: 1023127060,
        date_uploaded: "2024-03-29 11:47:34",
        date_uploaded_unix: 1711709254,
      },
      {
        url: "https://yts.mx/torrent/download/5A387F2F77285A2A487749AA3B762F377433B3FC",
        hash: "5A387F2F77285A2A487749AA3B762F377433B3FC",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 100,
        peers: 83,
        size: "1.96 GB",
        size_bytes: 2104533975,
        date_uploaded: "2024-03-29 12:43:50",
        date_uploaded_unix: 1711712630,
      },
    ],
    date_uploaded: "2024-03-29 11:47:34",
    date_uploaded_unix: 1711709254,
  },
  {
    id: 60778,
    url: "https://yts.mx/movies/clash-of-the-empires-2012",
    imdb_code: "tt2456594",
    title: "Clash of the Empires",
    title_english: "Clash of the Empires",
    title_long: "Clash of the Empires (2012)",
    slug: "clash-of-the-empires-2012",
    year: 2012,
    rating: 2.2,
    runtime: 87,
    genres: ["Action", "Adventure", "Fantasy"],
    summary:
      "In an age long ago, the last village of clever, peace-loving Hobbits is attacked and enslaved by the Java Men, komodo-worshiping, dragon-riding cannibals. Now the young Hobbit Goben, along with his father and sister, must seek help from the \"giants\" (human hunters) to find the Javas' lair and rescue the last surviving Hobbits, Goben's mother among them. In their quest to destroy the Javas, the heroic partnership of humans and Hobbits will transform both species forever.—The Asylum",
    description_full:
      "In an age long ago, the last village of clever, peace-loving Hobbits is attacked and enslaved by the Java Men, komodo-worshiping, dragon-riding cannibals. Now the young Hobbit Goben, along with his father and sister, must seek help from the \"giants\" (human hunters) to find the Javas' lair and rescue the last surviving Hobbits, Goben's mother among them. In their quest to destroy the Javas, the heroic partnership of humans and Hobbits will transform both species forever.—The Asylum",
    synopsis:
      "In an age long ago, the last village of clever, peace-loving Hobbits is attacked and enslaved by the Java Men, komodo-worshiping, dragon-riding cannibals. Now the young Hobbit Goben, along with his father and sister, must seek help from the \"giants\" (human hunters) to find the Javas' lair and rescue the last surviving Hobbits, Goben's mother among them. In their quest to destroy the Javas, the heroic partnership of humans and Hobbits will transform both species forever.—The Asylum",
    yt_trailer_code: "ooLk7g0k18s",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/clash_of_the_empires_2012/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/clash_of_the_empires_2012/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/clash_of_the_empires_2012/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/clash_of_the_empires_2012/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/clash_of_the_empires_2012/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/FE3C16A251D404B19A0A3B59E59564EBFFCCBBA2",
        hash: "FE3C16A251D404B19A0A3B59E59564EBFFCCBBA2",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "798.03 MB",
        size_bytes: 836795105,
        date_uploaded: "2024-03-30 01:10:09",
        date_uploaded_unix: 1711757409,
      },
      {
        url: "https://yts.mx/torrent/download/177E50D86A2AAABE4BC6C4922E5466C067F4297C",
        hash: "177E50D86A2AAABE4BC6C4922E5466C067F4297C",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.6 GB",
        size_bytes: 1717986918,
        date_uploaded: "2024-03-30 03:24:24",
        date_uploaded_unix: 1711765464,
      },
    ],
    date_uploaded: "2024-03-30 01:10:09",
    date_uploaded_unix: 1711757409,
  },
  {
    id: 60777,
    url: "https://yts.mx/movies/alpha-and-omega-2-a-howl-iday-adventure-2013",
    imdb_code: "tt3111728",
    title: "Alpha and Omega 2: A Howl-iday Adventure",
    title_english: "Alpha and Omega 2: A Howl-iday Adventure",
    title_long: "Alpha and Omega 2: A Howl-iday Adventure (2013)",
    slug: "alpha-and-omega-2-a-howl-iday-adventure-2013",
    year: 2013,
    rating: 4.7,
    runtime: 45,
    genres: ["Action", "Adventure", "Animation", "Comedy", "Family"],
    summary:
      'Kate & Humphrey and their 3 wolf cubs (Stinky, Claudette and Runt) are happily preparing to celebrate their first winter together when their smallest cub, Runt, mysteriously disappears. They must now go on a new journey across the wilderness to find and bring back Runt before the winter snows block their way home. While their adventure does not end exactly as planned, Kate & Humphrey discover that "Home is where the Family Is."—Lionsgate',
    description_full:
      'Kate & Humphrey and their 3 wolf cubs (Stinky, Claudette and Runt) are happily preparing to celebrate their first winter together when their smallest cub, Runt, mysteriously disappears. They must now go on a new journey across the wilderness to find and bring back Runt before the winter snows block their way home. While their adventure does not end exactly as planned, Kate & Humphrey discover that "Home is where the Family Is."—Lionsgate',
    synopsis:
      'Kate & Humphrey and their 3 wolf cubs (Stinky, Claudette and Runt) are happily preparing to celebrate their first winter together when their smallest cub, Runt, mysteriously disappears. They must now go on a new journey across the wilderness to find and bring back Runt before the winter snows block their way home. While their adventure does not end exactly as planned, Kate & Humphrey discover that "Home is where the Family Is."—Lionsgate',
    yt_trailer_code: "Gb_vl-ZQQUs",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/alpha_and_omega_2_a_howl_iday_adventure_2013/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/alpha_and_omega_2_a_howl_iday_adventure_2013/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/alpha_and_omega_2_a_howl_iday_adventure_2013/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/alpha_and_omega_2_a_howl_iday_adventure_2013/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/alpha_and_omega_2_a_howl_iday_adventure_2013/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/CF077BDC16FA19634C90F77FB4DA2C2789FDE84D",
        hash: "CF077BDC16FA19634C90F77FB4DA2C2789FDE84D",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "415.87 MB",
        size_bytes: 436071301,
        date_uploaded: "2024-03-29 10:04:39",
        date_uploaded_unix: 1711703079,
      },
      {
        url: "https://yts.mx/torrent/download/E272DDC3E570A512D6766F23B6B7F69A59566B4D",
        hash: "E272DDC3E570A512D6766F23B6B7F69A59566B4D",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "852.15 MB",
        size_bytes: 893544038,
        date_uploaded: "2024-03-29 10:59:47",
        date_uploaded_unix: 1711706387,
      },
    ],
    date_uploaded: "2024-03-29 10:04:39",
    date_uploaded_unix: 1711703079,
  },
  {
    id: 60776,
    url: "https://yts.mx/movies/kings-of-south-beach-2007",
    imdb_code: "tt0780059",
    title: "Kings of South Beach",
    title_english: "Kings of South Beach",
    title_long: "Kings of South Beach (2007)",
    slug: "kings-of-south-beach-2007",
    year: 2007,
    rating: 5.1,
    runtime: 90,
    genres: ["Crime", "Drama"],
    summary:
      "Chris Troiano runs South Beach (greater Miami)'s most popular nightclub, a recreational goldmine. Fellow New York immigrant Andy Burnett quickly rises from bouncer on trial to Troiano's trusted security chief and right hand. Thus he slowly discovers the club's entanglement with both the Russian mafia and domestic mob king Allie Boy, obviously involved in murders and arson. Andy is in fact an undercover cop, but risks losing trust with all superiors, except his immediate chief, so a trap must urgently be set.—KGF Vissers",
    description_full:
      "Chris Troiano runs South Beach (greater Miami)'s most popular nightclub, a recreational goldmine. Fellow New York immigrant Andy Burnett quickly rises from bouncer on trial to Troiano's trusted security chief and right hand. Thus he slowly discovers the club's entanglement with both the Russian mafia and domestic mob king Allie Boy, obviously involved in murders and arson. Andy is in fact an undercover cop, but risks losing trust with all superiors, except his immediate chief, so a trap must urgently be set.—KGF Vissers",
    synopsis:
      "Chris Troiano runs South Beach (greater Miami)'s most popular nightclub, a recreational goldmine. Fellow New York immigrant Andy Burnett quickly rises from bouncer on trial to Troiano's trusted security chief and right hand. Thus he slowly discovers the club's entanglement with both the Russian mafia and domestic mob king Allie Boy, obviously involved in murders and arson. Andy is in fact an undercover cop, but risks losing trust with all superiors, except his immediate chief, so a trap must urgently be set.—KGF Vissers",
    yt_trailer_code: "w_HvasX8Tw8",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/kings_of_south_beach_2007/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/kings_of_south_beach_2007/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/kings_of_south_beach_2007/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/kings_of_south_beach_2007/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/kings_of_south_beach_2007/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/69A15461685A43030D35D8291DFB50731ECAE277",
        hash: "69A15461685A43030D35D8291DFB50731ECAE277",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "835.63 MB",
        size_bytes: 876221563,
        date_uploaded: "2024-03-29 17:36:12",
        date_uploaded_unix: 1711730172,
      },
    ],
    date_uploaded: "2024-03-29 17:36:12",
    date_uploaded_unix: 1711730172,
  },
  {
    id: 60775,
    url: "https://yts.mx/movies/adele-live-at-the-royal-albert-hall-2011",
    imdb_code: "tt2122272",
    title: "Adele Live at the Royal Albert Hall",
    title_english: "Adele Live at the Royal Albert Hall",
    title_long: "Adele Live at the Royal Albert Hall (2011)",
    slug: "adele-live-at-the-royal-albert-hall-2011",
    year: 2011,
    rating: 8.6,
    runtime: 90,
    genres: ["Documentary", "Music"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "5Oio8V3e3WU",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/adele_live_at_the_royal_albert_hall_2011/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/adele_live_at_the_royal_albert_hall_2011/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/adele_live_at_the_royal_albert_hall_2011/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/adele_live_at_the_royal_albert_hall_2011/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/adele_live_at_the_royal_albert_hall_2011/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/781DEDFF7BA274EF9215C1336E058E1B54A53899",
        hash: "781DEDFF7BA274EF9215C1336E058E1B54A53899",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "917.95 MB",
        size_bytes: 962540339,
        date_uploaded: "2024-03-29 16:50:15",
        date_uploaded_unix: 1711727415,
      },
      {
        url: "https://yts.mx/torrent/download/FB07B40F613B1B8D39978DD720E54436D1E449FB",
        hash: "FB07B40F613B1B8D39978DD720E54436D1E449FB",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.84 GB",
        size_bytes: 1975684956,
        date_uploaded: "2024-03-29 18:21:31",
        date_uploaded_unix: 1711732891,
      },
    ],
    date_uploaded: "2024-03-29 16:50:15",
    date_uploaded_unix: 1711727415,
  },
  {
    id: 60774,
    url: "https://yts.mx/movies/wuthering-heights-2003",
    imdb_code: "tt0367245",
    title: "Wuthering Heights",
    title_english: "Wuthering Heights",
    title_long: "Wuthering Heights (2003)",
    slug: "wuthering-heights-2003",
    year: 2003,
    rating: 4.1,
    runtime: 90,
    genres: ["Drama", "Musical", "Romance"],
    summary:
      "In this loose modern adaptation of the classic novel, Cate and her adopted brother Heath grow up together and fall in love once they hit their teens. Her desire to leave the simple life conflicts with his wishes for them to stay at the Heights (their lighthouse home) together. It gets worse when her father dies, leaving everything to Cate's awful older brother Hendrix, who hates Heath. Cate ends up marrying the wealthy Edward, while the bitter Heath becomes a rock star and exacts revenge upon those who mistreated him. Once he and Cate start an affair, tragedy follows.—cupcakes",
    description_full:
      "In this loose modern adaptation of the classic novel, Cate and her adopted brother Heath grow up together and fall in love once they hit their teens. Her desire to leave the simple life conflicts with his wishes for them to stay at the Heights (their lighthouse home) together. It gets worse when her father dies, leaving everything to Cate's awful older brother Hendrix, who hates Heath. Cate ends up marrying the wealthy Edward, while the bitter Heath becomes a rock star and exacts revenge upon those who mistreated him. Once he and Cate start an affair, tragedy follows.—cupcakes",
    synopsis:
      "In this loose modern adaptation of the classic novel, Cate and her adopted brother Heath grow up together and fall in love once they hit their teens. Her desire to leave the simple life conflicts with his wishes for them to stay at the Heights (their lighthouse home) together. It gets worse when her father dies, leaving everything to Cate's awful older brother Hendrix, who hates Heath. Cate ends up marrying the wealthy Edward, while the bitter Heath becomes a rock star and exacts revenge upon those who mistreated him. Once he and Cate start an affair, tragedy follows.—cupcakes",
    yt_trailer_code: "Aw_esK7Pmto",
    language: "en",
    mpa_rating: "PG-13",
    background_image:
      "https://yts.mx/assets/images/movies/wuthering_heights_2003/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/wuthering_heights_2003/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/wuthering_heights_2003/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/wuthering_heights_2003/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/wuthering_heights_2003/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/31C5FC9E5D7BB676A7F47283D2A9909698333927",
        hash: "31C5FC9E5D7BB676A7F47283D2A9909698333927",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "814.1 MB",
        size_bytes: 853645722,
        date_uploaded: "2024-03-30 00:00:21",
        date_uploaded_unix: 1711753221,
      },
    ],
    date_uploaded: "2024-03-30 00:00:21",
    date_uploaded_unix: 1711753221,
  },
  {
    id: 60773,
    url: "https://yts.mx/movies/mars-needs-women-1968",
    imdb_code: "tt0060672",
    title: "Mars Needs Women",
    title_english: "Mars Needs Women",
    title_long: "Mars Needs Women (1968)",
    slug: "mars-needs-women-1968",
    year: 1968,
    rating: 3.2,
    runtime: 83,
    genres: ["Sci-Fi"],
    summary:
      'After receiving a series of messages from outer space all decoded to be "Mars Needs Women", the United States Decoding Center in Houston receives a visit from Dop, the leader of a group of five Martians on an experimental voyage to Earth. Because of a genetic problem, Martians are producing virtually only male offspring and thus need to import women for the survival of the species. The Martians\' non-hostile mission is to bring back to Mars five fertile and single human women. Those at the Center see the mission as a hostile one and as such the Martians decide to carry out their mission as inconspicuously as possible without the cooperation of the authorities by posing as Earthlings. Of the potential women they spy which includes strippers, co-eds and flight attendants, the one they believe is the most conducive to success of the project is the beautiful Dr. Marjorie Bolen, an expert in space genetics. In pursuing her, Dop falls in love with Dr. Bolen. But the Martians have to complete the mission before the authorities, which includes Dr. Bolen, find their secret hiding location.—Huggo',
    description_full:
      'After receiving a series of messages from outer space all decoded to be "Mars Needs Women", the United States Decoding Center in Houston receives a visit from Dop, the leader of a group of five Martians on an experimental voyage to Earth. Because of a genetic problem, Martians are producing virtually only male offspring and thus need to import women for the survival of the species. The Martians\' non-hostile mission is to bring back to Mars five fertile and single human women. Those at the Center see the mission as a hostile one and as such the Martians decide to carry out their mission as inconspicuously as possible without the cooperation of the authorities by posing as Earthlings. Of the potential women they spy which includes strippers, co-eds and flight attendants, the one they believe is the most conducive to success of the project is the beautiful Dr. Marjorie Bolen, an expert in space genetics. In pursuing her, Dop falls in love with Dr. Bolen. But the Martians have to complete the mission before the authorities, which includes Dr. Bolen, find their secret hiding location.—Huggo',
    synopsis:
      'After receiving a series of messages from outer space all decoded to be "Mars Needs Women", the United States Decoding Center in Houston receives a visit from Dop, the leader of a group of five Martians on an experimental voyage to Earth. Because of a genetic problem, Martians are producing virtually only male offspring and thus need to import women for the survival of the species. The Martians\' non-hostile mission is to bring back to Mars five fertile and single human women. Those at the Center see the mission as a hostile one and as such the Martians decide to carry out their mission as inconspicuously as possible without the cooperation of the authorities by posing as Earthlings. Of the potential women they spy which includes strippers, co-eds and flight attendants, the one they believe is the most conducive to success of the project is the beautiful Dr. Marjorie Bolen, an expert in space genetics. In pursuing her, Dop falls in love with Dr. Bolen. But the Martians have to complete the mission before the authorities, which includes Dr. Bolen, find their secret hiding location.—Huggo',
    yt_trailer_code: "",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/mars_needs_women_1968/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/mars_needs_women_1968/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/mars_needs_women_1968/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/mars_needs_women_1968/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/mars_needs_women_1968/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/3F326325294D0B9D29246FAEEEFA58B4774E1339",
        hash: "3F326325294D0B9D29246FAEEEFA58B4774E1339",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "757.11 MB",
        size_bytes: 793887375,
        date_uploaded: "2024-03-29 18:49:13",
        date_uploaded_unix: 1711734553,
      },
    ],
    date_uploaded: "2024-03-29 18:49:13",
    date_uploaded_unix: 1711734553,
  },
  {
    id: 60772,
    url: "https://yts.mx/movies/hotel-pacific-1975",
    imdb_code: "tt0075454",
    title: "Hotel Pacific",
    title_english: "Hotel Pacific",
    title_long: "Hotel Pacific (1975)",
    slug: "hotel-pacific-1975",
    year: 1975,
    rating: 7.2,
    runtime: 94,
    genres: ["Drama"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "",
    language: "pl",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/hotel_pacific_1975/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/hotel_pacific_1975/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/hotel_pacific_1975/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/hotel_pacific_1975/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/hotel_pacific_1975/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/73D63107B9C99D0150A2C44FB8AE3FDAA348CA6A",
        hash: "73D63107B9C99D0150A2C44FB8AE3FDAA348CA6A",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "878.78 MB",
        size_bytes: 921467617,
        date_uploaded: "2024-03-29 20:34:41",
        date_uploaded_unix: 1711740881,
      },
      {
        url: "https://yts.mx/torrent/download/5E760F5AD13CC2A79E7BD5FE6ED74DE9DFBABD86",
        hash: "5E760F5AD13CC2A79E7BD5FE6ED74DE9DFBABD86",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "1.59 GB",
        size_bytes: 1707249500,
        date_uploaded: "2024-03-29 21:38:59",
        date_uploaded_unix: 1711744739,
      },
    ],
    date_uploaded: "2024-03-29 20:34:41",
    date_uploaded_unix: 1711740881,
  },
  {
    id: 60771,
    url: "https://yts.mx/movies/first-descent-2005",
    imdb_code: "tt0455475",
    title: "First Descent",
    title_english: "First Descent",
    title_long: "First Descent (2005)",
    slug: "first-descent-2005",
    year: 2005,
    rating: 7,
    runtime: 110,
    genres: ["Documentary", "Sport"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "TIu0oRJKAbw",
    language: "en",
    mpa_rating: "PG-13",
    background_image:
      "https://yts.mx/assets/images/movies/first_descent_2005/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/first_descent_2005/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/first_descent_2005/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/first_descent_2005/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/first_descent_2005/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/BE0EEF723DA729D082B78392DCA5E8BA67E15BFE",
        hash: "BE0EEF723DA729D082B78392DCA5E8BA67E15BFE",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "1016.09 MB",
        size_bytes: 1065447588,
        date_uploaded: "2024-03-29 15:52:34",
        date_uploaded_unix: 1711723954,
      },
      {
        url: "https://yts.mx/torrent/download/7B433C9DA0BE49F43CCB48B6D6D2DF45745C83A3",
        hash: "7B433C9DA0BE49F43CCB48B6D6D2DF45745C83A3",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "2.04 GB",
        size_bytes: 2190433321,
        date_uploaded: "2024-03-29 17:02:18",
        date_uploaded_unix: 1711728138,
      },
    ],
    date_uploaded: "2024-03-29 15:52:34",
    date_uploaded_unix: 1711723954,
  },
  {
    id: 60769,
    url: "https://yts.mx/movies/the-dissidents-2017",
    imdb_code: "tt6025806",
    title: "The Dissidents",
    title_english: "The Dissidents",
    title_long: "The Dissidents (2017)",
    slug: "the-dissidents-2017",
    year: 2017,
    rating: 6.4,
    runtime: 90,
    genres: ["Action", "Comedy"],
    summary:
      'Fast-paced action comedy "The Dissidents" takes us back to the 1980s. Three Estonian guys flee Soviet Union, because they want to have as awesome life in the free world as they\'ve seen in TV series "Miami Vice", "Knight Rider" and "Santa Barbara". Swedes welcome friends as real heroes who broke through the Iron Curtain. But as the media circus blows over, our dissidents discover that they\'ve become nothing more than tedious immigrants. To put food on the table, they must do something as lame as--work. But the boys are no quitters, so they come up with crazy new plans that should guarantee success in the Western world. That\'s when things go totally insane.',
    description_full:
      'Fast-paced action comedy "The Dissidents" takes us back to the 1980s. Three Estonian guys flee Soviet Union, because they want to have as awesome life in the free world as they\'ve seen in TV series "Miami Vice", "Knight Rider" and "Santa Barbara". Swedes welcome friends as real heroes who broke through the Iron Curtain. But as the media circus blows over, our dissidents discover that they\'ve become nothing more than tedious immigrants. To put food on the table, they must do something as lame as--work. But the boys are no quitters, so they come up with crazy new plans that should guarantee success in the Western world. That\'s when things go totally insane.',
    synopsis:
      'Fast-paced action comedy "The Dissidents" takes us back to the 1980s. Three Estonian guys flee Soviet Union, because they want to have as awesome life in the free world as they\'ve seen in TV series "Miami Vice", "Knight Rider" and "Santa Barbara". Swedes welcome friends as real heroes who broke through the Iron Curtain. But as the media circus blows over, our dissidents discover that they\'ve become nothing more than tedious immigrants. To put food on the table, they must do something as lame as--work. But the boys are no quitters, so they come up with crazy new plans that should guarantee success in the Western world. That\'s when things go totally insane.',
    yt_trailer_code: "DOAgslk9Vno",
    language: "et",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/the_dissidents_2017/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/the_dissidents_2017/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/the_dissidents_2017/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/the_dissidents_2017/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/the_dissidents_2017/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/A4F88FB7D19048A56FDD05DA152E29E553178D46",
        hash: "A4F88FB7D19048A56FDD05DA152E29E553178D46",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "848.98 MB",
        size_bytes: 890220052,
        date_uploaded: "2024-03-29 18:55:15",
        date_uploaded_unix: 1711734915,
      },
      {
        url: "https://yts.mx/torrent/download/162A22D96D4CE4CB46D068B063DD7A3E101109B6",
        hash: "162A22D96D4CE4CB46D068B063DD7A3E101109B6",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "1.7 GB",
        size_bytes: 1825361101,
        date_uploaded: "2024-03-29 19:55:55",
        date_uploaded_unix: 1711738555,
      },
    ],
    date_uploaded: "2024-03-29 18:55:15",
    date_uploaded_unix: 1711734915,
  },
  {
    id: 60767,
    url: "https://yts.mx/movies/nils-karlsson-pyssling-1990",
    imdb_code: "tt0100264",
    title: "Nils Karlsson Pyssling",
    title_english: "Nils Karlsson Pyssling",
    title_long: "Nils Karlsson Pyssling (1990)",
    slug: "nils-karlsson-pyssling-1990",
    year: 1990,
    rating: 5.7,
    runtime: 75,
    genres: ["Family", "Fantasy"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "1zpXXtVByws",
    language: "sv",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/nils_karlsson_pyssling_1990/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/nils_karlsson_pyssling_1990/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/nils_karlsson_pyssling_1990/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/nils_karlsson_pyssling_1990/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/nils_karlsson_pyssling_1990/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/4F0D20E80184C39775CB1827576A2EDADE2385D9",
        hash: "4F0D20E80184C39775CB1827576A2EDADE2385D9",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 19,
        peers: 6,
        size: "658.86 MB",
        size_bytes: 690864783,
        date_uploaded: "2024-03-29 14:18:26",
        date_uploaded_unix: 1711718306,
      },
      {
        url: "https://yts.mx/torrent/download/0EAC5086049455E2097CE0E5106761614D2BDF18",
        hash: "0EAC5086049455E2097CE0E5106761614D2BDF18",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 40,
        peers: 10,
        size: "1.19 GB",
        size_bytes: 1277752771,
        date_uploaded: "2024-03-29 15:12:13",
        date_uploaded_unix: 1711721533,
      },
    ],
    date_uploaded: "2024-03-29 14:18:26",
    date_uploaded_unix: 1711718306,
  },
  {
    id: 60768,
    url: "https://yts.mx/movies/aurora-teagarden-mysteries-a-game-of-cat-and-mouse-2019",
    imdb_code: "tt9759864",
    title: "Aurora Teagarden Mysteries: A Game of Cat and Mouse",
    title_english: "Aurora Teagarden Mysteries: A Game of Cat and Mouse",
    title_long: "Aurora Teagarden Mysteries: A Game of Cat and Mouse (2019)",
    slug: "aurora-teagarden-mysteries-a-game-of-cat-and-mouse-2019",
    year: 2019,
    rating: 7.1,
    runtime: 84,
    genres: ["Crime", "Mystery"],
    summary:
      "Aurora Teagarden - Ro to her friends - is a librarian and president of the Real Murders Discussion Club in the town of Lawrenceton, she seen as the smartest of the club members when it comes to those real life murders. Who she brings new to the club are her younger cousin, college student Phillip Pifer, which does not sit well with Ro's mother, realtor Aida Teagarden who only sees trouble in talking about murder, and relatively new friend, Nick Miller, a Psychology professor at the local college, Ro and Nick who seem to be on the cusp of a relationship. In Ro setting up a day before a meeting in leading a discussion about the Lipstick Murders, the club members arrive to discover that Ro's discussion materials have either been vandalized or stolen, the vandal who left a calling card of sorts in some literary quote scribbled on one of Ro's Lipstick Murders crime scene photos. When Aida's office is subsequently vandalized with a similar literary quote calling card on another Lipstick Murders crime scene photo and some of Ro's materials stolen in the previous crime, Ro, on other evidence, is assumed to be the common bond and the target of whatever the criminal's actions. Police Chief Lynn Smith, and her husband, Homicide Detective Arthur Smith - a Real Murders member himself much to Lynn's chagrin - look to anyone who may have a grudge against Ro. The suspects include: new club member Davis Mettle, who seems to resent Ro's superiority on the subject; Edward Irons, a regular at the library who blames Ro for among other things not having his self-published book stocked in the library; Nick's new T.A. Dina McMillan, an academically bright but socially insecure woman who seems to have a hate at first sight for Ro; and much to Ro's chagrin Valerie Wagner, a longtime family friend who reacts unusually to the fact of the crimes and who had access in being both Ro and Aida's cleaner with code access and keys to both properties. Although Lynn has always resented any assistance from the Real Murders club members especially Ro herself, she does somewhat welcome that of her friend and Nick's boss, Forensic Psychologist Bree Carson who may be able to provide additional insight beyond the on the surface evidence. This collective will have to work fast to discover the perpetrator as he or she has committed subsequent crimes - with the same signature of the literary quote on a photo and stolen items from the previous crime left at the scene - against people close to Ro, those crimes increasingly violent with arguably the end target being Ro herself.—Huggo",
    description_full:
      "Aurora Teagarden - Ro to her friends - is a librarian and president of the Real Murders Discussion Club in the town of Lawrenceton, she seen as the smartest of the club members when it comes to those real life murders. Who she brings new to the club are her younger cousin, college student Phillip Pifer, which does not sit well with Ro's mother, realtor Aida Teagarden who only sees trouble in talking about murder, and relatively new friend, Nick Miller, a Psychology professor at the local college, Ro and Nick who seem to be on the cusp of a relationship. In Ro setting up a day before a meeting in leading a discussion about the Lipstick Murders, the club members arrive to discover that Ro's discussion materials have either been vandalized or stolen, the vandal who left a calling card of sorts in some literary quote scribbled on one of Ro's Lipstick Murders crime scene photos. When Aida's office is subsequently vandalized with a similar literary quote calling card on another Lipstick Murders crime scene photo and some of Ro's materials stolen in the previous crime, Ro, on other evidence, is assumed to be the common bond and the target of whatever the criminal's actions. Police Chief Lynn Smith, and her husband, Homicide Detective Arthur Smith - a Real Murders member himself much to Lynn's chagrin - look to anyone who may have a grudge against Ro. The suspects include: new club member Davis Mettle, who seems to resent Ro's superiority on the subject; Edward Irons, a regular at the library who blames Ro for among other things not having his self-published book stocked in the library; Nick's new T.A. Dina McMillan, an academically bright but socially insecure woman who seems to have a hate at first sight for Ro; and much to Ro's chagrin Valerie Wagner, a longtime family friend who reacts unusually to the fact of the crimes and who had access in being both Ro and Aida's cleaner with code access and keys to both properties. Although Lynn has always resented any assistance from the Real Murders club members especially Ro herself, she does somewhat welcome that of her friend and Nick's boss, Forensic Psychologist Bree Carson who may be able to provide additional insight beyond the on the surface evidence. This collective will have to work fast to discover the perpetrator as he or she has committed subsequent crimes - with the same signature of the literary quote on a photo and stolen items from the previous crime left at the scene - against people close to Ro, those crimes increasingly violent with arguably the end target being Ro herself.—Huggo",
    synopsis:
      "Aurora Teagarden - Ro to her friends - is a librarian and president of the Real Murders Discussion Club in the town of Lawrenceton, she seen as the smartest of the club members when it comes to those real life murders. Who she brings new to the club are her younger cousin, college student Phillip Pifer, which does not sit well with Ro's mother, realtor Aida Teagarden who only sees trouble in talking about murder, and relatively new friend, Nick Miller, a Psychology professor at the local college, Ro and Nick who seem to be on the cusp of a relationship. In Ro setting up a day before a meeting in leading a discussion about the Lipstick Murders, the club members arrive to discover that Ro's discussion materials have either been vandalized or stolen, the vandal who left a calling card of sorts in some literary quote scribbled on one of Ro's Lipstick Murders crime scene photos. When Aida's office is subsequently vandalized with a similar literary quote calling card on another Lipstick Murders crime scene photo and some of Ro's materials stolen in the previous crime, Ro, on other evidence, is assumed to be the common bond and the target of whatever the criminal's actions. Police Chief Lynn Smith, and her husband, Homicide Detective Arthur Smith - a Real Murders member himself much to Lynn's chagrin - look to anyone who may have a grudge against Ro. The suspects include: new club member Davis Mettle, who seems to resent Ro's superiority on the subject; Edward Irons, a regular at the library who blames Ro for among other things not having his self-published book stocked in the library; Nick's new T.A. Dina McMillan, an academically bright but socially insecure woman who seems to have a hate at first sight for Ro; and much to Ro's chagrin Valerie Wagner, a longtime family friend who reacts unusually to the fact of the crimes and who had access in being both Ro and Aida's cleaner with code access and keys to both properties. Although Lynn has always resented any assistance from the Real Murders club members especially Ro herself, she does somewhat welcome that of her friend and Nick's boss, Forensic Psychologist Bree Carson who may be able to provide additional insight beyond the on the surface evidence. This collective will have to work fast to discover the perpetrator as he or she has committed subsequent crimes - with the same signature of the literary quote on a photo and stolen items from the previous crime left at the scene - against people close to Ro, those crimes increasingly violent with arguably the end target being Ro herself.—Huggo",
    yt_trailer_code: "",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/aurora_teagarden_mysteries_a_game_of_cat_and_mouse_2019/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/aurora_teagarden_mysteries_a_game_of_cat_and_mouse_2019/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/aurora_teagarden_mysteries_a_game_of_cat_and_mouse_2019/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/aurora_teagarden_mysteries_a_game_of_cat_and_mouse_2019/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/aurora_teagarden_mysteries_a_game_of_cat_and_mouse_2019/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/CB0FE3F12EACD8D7145B4B9974EFB3E7C68C226A",
        hash: "CB0FE3F12EACD8D7145B4B9974EFB3E7C68C226A",
        quality: "720p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "772.17 MB",
        size_bytes: 809678930,
        date_uploaded: "2024-03-29 17:11:06",
        date_uploaded_unix: 1711728666,
      },
      {
        url: "https://yts.mx/torrent/download/0CD8E5A8CC1F23FCCC42C6EDAFF3C779A717B8C3",
        hash: "0CD8E5A8CC1F23FCCC42C6EDAFF3C779A717B8C3",
        quality: "1080p",
        type: "web",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 100,
        peers: 37,
        size: "1.4 GB",
        size_bytes: 1503238554,
        date_uploaded: "2024-03-29 18:06:51",
        date_uploaded_unix: 1711732011,
      },
    ],
    date_uploaded: "2024-03-29 17:11:06",
    date_uploaded_unix: 1711728666,
  },
  {
    id: 60770,
    url: "https://yts.mx/movies/the-three-musketeers-1921",
    imdb_code: "tt0012752",
    title: "The Three Musketeers",
    title_english: "The Three Musketeers",
    title_long: "The Three Musketeers (1921)",
    slug: "the-three-musketeers-1921",
    year: 1921,
    rating: 6.9,
    runtime: 119,
    genres: ["Action", "Adventure", "Family", "Romance"],
    summary:
      "The young Gascon D'Artagnan arrives in Paris, his heart set on joining the king's Musketeers. He is taken under the wings of three of the most respected and feared Musketeers, Porthos, Aramis, and Athos. Together they fight to save France and the honor of a lady from the machinations of the powerful Cardinal Richelieu.—Jim Beaver",
    description_full:
      "The young Gascon D'Artagnan arrives in Paris, his heart set on joining the king's Musketeers. He is taken under the wings of three of the most respected and feared Musketeers, Porthos, Aramis, and Athos. Together they fight to save France and the honor of a lady from the machinations of the powerful Cardinal Richelieu.—Jim Beaver",
    synopsis:
      "The young Gascon D'Artagnan arrives in Paris, his heart set on joining the king's Musketeers. He is taken under the wings of three of the most respected and feared Musketeers, Porthos, Aramis, and Athos. Together they fight to save France and the honor of a lady from the machinations of the powerful Cardinal Richelieu.—Jim Beaver",
    yt_trailer_code: "",
    language: "xx",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/the_three_musketeers_1921/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/the_three_musketeers_1921/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/the_three_musketeers_1921/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/the_three_musketeers_1921/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/the_three_musketeers_1921/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/D9F73B421205D92BD42A44C8DA47BD264A6E932C",
        hash: "D9F73B421205D92BD42A44C8DA47BD264A6E932C",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "1.22 GB",
        size_bytes: 1309965025,
        date_uploaded: "2024-03-29 13:17:28",
        date_uploaded_unix: 1711714648,
      },
      {
        url: "https://yts.mx/torrent/download/905E5DF377EEBA9B2862B7FAABA0F6D8B0E12976",
        hash: "905E5DF377EEBA9B2862B7FAABA0F6D8B0E12976",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "5.1",
        seeds: 0,
        peers: 0,
        size: "2.51 GB",
        size_bytes: 2695091978,
        date_uploaded: "2024-03-29 16:27:48",
        date_uploaded_unix: 1711726068,
      },
    ],
    date_uploaded: "2024-03-29 13:17:28",
    date_uploaded_unix: 1711714648,
  },
  {
    id: 60764,
    url: "https://yts.mx/movies/to-the-arctic-3d-2012",
    imdb_code: "tt2073128",
    title: "To the Arctic 3D",
    title_english: "To the Arctic 3D",
    title_long: "To the Arctic 3D (2012)",
    slug: "to-the-arctic-3d-2012",
    year: 2012,
    rating: 6.6,
    runtime: 40,
    genres: ["Documentary"],
    summary: "",
    description_full: "",
    synopsis: "",
    yt_trailer_code: "MVD4VhdNo1A",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/to_the_arctic_3d_2012/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/to_the_arctic_3d_2012/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/to_the_arctic_3d_2012/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/to_the_arctic_3d_2012/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/to_the_arctic_3d_2012/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/B3F12C2C2A43A43D05539D275D9308E326AFF890",
        hash: "B3F12C2C2A43A43D05539D275D9308E326AFF890",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "372.32 MB",
        size_bytes: 390405816,
        date_uploaded: "2024-03-29 18:21:39",
        date_uploaded_unix: 1711732899,
      },
    ],
    date_uploaded: "2024-03-29 18:21:39",
    date_uploaded_unix: 1711732899,
  },
  {
    id: 60763,
    url: "https://yts.mx/movies/mchales-navy-1964",
    imdb_code: "tt0058336",
    title: "McHale's Navy",
    title_english: "McHale's Navy",
    title_long: "McHale's Navy (1964)",
    slug: "mchales-navy-1964",
    year: 1964,
    rating: 6.4,
    runtime: 93,
    genres: ["Comedy", "War"],
    summary:
      "The crew of PT-73 get into trouble when they back the wrong horse in a race. Now they have to come up with a way to raise the money to pay off the winners.—Brian W Martz",
    description_full:
      "The crew of PT-73 get into trouble when they back the wrong horse in a race. Now they have to come up with a way to raise the money to pay off the winners.—Brian W Martz",
    synopsis:
      "The crew of PT-73 get into trouble when they back the wrong horse in a race. Now they have to come up with a way to raise the money to pay off the winners.—Brian W Martz",
    yt_trailer_code: "",
    language: "en",
    mpa_rating: "",
    background_image:
      "https://yts.mx/assets/images/movies/mchales_navy_1964/background.jpg",
    background_image_original:
      "https://yts.mx/assets/images/movies/mchales_navy_1964/background.jpg",
    small_cover_image:
      "https://yts.mx/assets/images/movies/mchales_navy_1964/small-cover.jpg",
    medium_cover_image:
      "https://yts.mx/assets/images/movies/mchales_navy_1964/medium-cover.jpg",
    large_cover_image:
      "https://yts.mx/assets/images/movies/mchales_navy_1964/large-cover.jpg",
    state: "ok",
    torrents: [
      {
        url: "https://yts.mx/torrent/download/701A4F8EE2F3AA041E3A758928817391EE51716E",
        hash: "701A4F8EE2F3AA041E3A758928817391EE51716E",
        quality: "720p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "852.95 MB",
        size_bytes: 894382899,
        date_uploaded: "2024-03-29 12:44:06",
        date_uploaded_unix: 1711712646,
      },
      {
        url: "https://yts.mx/torrent/download/6315FA466A0676CD6D72FDC3822919250AD04E7F",
        hash: "6315FA466A0676CD6D72FDC3822919250AD04E7F",
        quality: "1080p",
        type: "bluray",
        is_repack: "0",
        video_codec: "x264",
        bit_depth: "8",
        audio_channels: "2.0",
        seeds: 0,
        peers: 0,
        size: "1.55 GB",
        size_bytes: 1664299827,
        date_uploaded: "2024-03-29 14:08:13",
        date_uploaded_unix: 1711717693,
      },
    ],
    date_uploaded: "2024-03-29 12:44:06",
    date_uploaded_unix: 1711712646,
  },
  {
    large_cover_image:
      "https://yts.mx/assets/images/movies/heart_of_the_hunter_2024/large-cover.jpg",
  },
  {
    large_cover_image:
      "https://yts.mx/assets/images/movies/madu_2024/large-cover.jpg",
  },
  {
    large_cover_image:
      "https://yts.mx/assets/images/movies/the_beautiful_summer_2023/large-cover.jpg",
  },
  {
    large_cover_image:
      "https://yts.mx/assets/images/movies/marinette_2023/large-cover.jpg",
  },
];

export default movieData;
